@startuml
Client -> Server: Authentication Request
note left: GET /login?user_id=firstUser&password=example
Client <-- Server: Authentication Response
note right: with JWT token

Client -> Server: Create a new booking
note left: POST /bookings {"content": "example"}
Client <-- Server : New booking response
@enduml